
import HomePage from '@/components/HomePage';

import Main from '@/components/Main';



/*<title>Create Next App</title>
  <meta name="description" content="Generated by create next app" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="icon" href="/favicon.ico" />
*/

export async function getAllApps() {
  const response = await fetch("https://uztechtips.onrender.com/api/v1/getApps");
  return await response.json();
}

export async function getStaticProps() {

  const apps = await getAllApps();

  return {
    props : {
      apps
    },
    revalidate : 10800
  }
}


export default function Home(props) {
  
  return (
    <>
      <Main apps={props.apps}>
        <HomePage/>
      </Main>
    </>
  );
}
